<?php
/**
 * WP-CLI Commands for Easy Theme
 *
 * @package EasyTheme
 */

namespace EasyTheme\CLI;

use EasyTheme\Core\ServiceInterface;
use WP_CLI;

class MakeCommand implements ServiceInterface {

	/**
	 * Register the CLI command.
	 */
	public function register() {
		// Only register if WP_CLI is running
		if ( ! defined( 'WP_CLI' ) || ! WP_CLI ) {
			return;
		}

		WP_CLI::add_command( 'easy make:block', array( $this, 'make_block' ) );
	}

	/**
	 * Generates a template part and block.json for an SCF/ACF Gutenberg block!
	 *
	 * ## OPTIONS
	 *
	 * <name>
	 * : The name of the block (e.g., HeroSection).
	 *
	 * ## EXAMPLES
	 *
	 *     wp easy make:block HeroSection
	 *
	 * @param array $args
	 * @param array $assoc_args
	 */
	public function make_block( $args, $assoc_args ) {
		$block_name_raw = sanitize_text_field( $args[0] );
		
		// Kebab case conversion for block.json: HeroSection -> hero-section
		$block_slug = strtolower( preg_replace( '/(?<!^)[A-Z]/', '-$0', $block_name_raw ) );

		if ( empty( $block_slug ) ) {
			WP_CLI::error( 'Please provide a valid block name.' );
		}

		// Create block specific folder
		$dir_path = get_template_directory() . '/template-parts/blocks/' . $block_slug;
		if ( ! file_exists( $dir_path ) ) {
			mkdir( $dir_path, 0755, true );
		}

		$php_file_path = $dir_path . '/render.php';
		$json_file_path = $dir_path . '/block.json';

		if ( file_exists( $php_file_path ) || file_exists( $json_file_path ) ) {
			WP_CLI::error( 'Block file already exists in ' . $dir_path );
		}

		// JSON Stub for SCF/ACF Block
		$json_stub = <<<EOT
{
    "name": "acf/{$block_slug}",
    "title": "{$block_name_raw}",
    "description": "A custom block generated by EasyTheme.",
    "style": [ "file:./style.css" ],
    "category": "formatting",
    "icon": "welcome-widgets-menus",
    "keywords": ["{$block_slug}", "easy"],
    "acf": {
        "mode": "preview",
        "renderTemplate": "render.php"
    },
    "supports": {
        "align": true,
        "jsx": true
    }
}
EOT;

		// PHP Stub
		$php_stub = <<<EOT
<?php
/**
 * Block: {$block_name_raw}
 * 
 * @package EasyTheme
 */

\$classes = ['block-{$block_slug}', 'relative', 'my-8'];

// Support custom "className" values set in the block editor.
if ( ! empty( \$block['className'] ) ) {
	\$classes[] = \$block['className'];
}

// Support alignment settings.
if ( ! empty( \$block['align'] ) ) {
	\$classes[] = 'align' . \$block['align'];
}
?>

<div class="<?php echo esc_attr( implode( ' ', \$classes ) ); ?>">
	<!-- Your SCF Block HTML goes here. Tailwind fully supported. -->
	<h2 class="text-2xl font-serif text-gray-900">Custom {$block_name_raw} Block</h2>
	<!-- Example SCF Field usage: echo esc_html(get_field('heading')); -->
</div>
EOT;

		// Save files
		file_put_contents( $json_file_path, $json_stub );
		file_put_contents( $php_file_path, $php_stub );

		WP_CLI::success( "SCF Block '{$block_name_raw}' created successfully!" );
		WP_CLI::log( "Location: {$dir_path}" );
		WP_CLI::log( "Action: Be sure to initialize block.json files in your 'init' hook via register_block_type()!" );
	}
}
